name: Build & Deploy Angular Application to Firebase

on:
  push:
    branches: [main] # Only trigger on master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - uses: w9jds/firebase-action@v2.0.0
        with:
          args: use default
      - uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
